#!/usr/bin/env python3
"""
length_analysis.py
==================
Analyzes whether response length predicts correctness across models.

The universal finding: every model writes longer responses for incorrect pairs.
This script quantifies that relationship, tests whether it's statistically
robust, estimates effect size, and checks if the confound is driven by
pair difficulty (GT class distribution).

Uses the per-model adherence CSVs already generated by syntax_adherence.py,
which contain: pair_id, correct, ground_truth, response_len, adherence_score.

Usage:
    python length_analysis.py              # all models
    python length_analysis.py --model gpt4o gpt54
    python length_analysis.py --output results/length/
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy import stats as scipy_stats

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from lib.loader import list_model_datasets

DEFAULT_OUTPUT = ROOT / "adherence_results"

# ── helpers ───────────────────────────────────────────────────────────────────

def sig_label(p):
    if p < 0.001: return "***"
    if p < 0.01:  return "**"
    if p < 0.05:  return "*"
    return "ns"

def cohens_d(a, b):
    n1, n2 = len(a), len(b)
    if n1 < 2 or n2 < 2:
        return float("nan")
    pooled = np.sqrt(((n1 - 1) * a.var() + (n2 - 1) * b.var()) / (n1 + n2 - 2))
    return (a.mean() - b.mean()) / pooled if pooled > 0 else float("nan")

# ── per-model analysis ────────────────────────────────────────────────────────

def analyze_model(name: str, output_dir: Path) -> dict | None:
    csv_path = output_dir / f"{name}_adherence.csv"
    if not csv_path.exists():
        print(f"  [skip] {name}: {csv_path.name} not found — run syntax_adherence.py first")
        return None

    df = pd.read_csv(csv_path)
    if "response_len" not in df.columns or "correct" not in df.columns:
        print(f"  [skip] {name}: missing required columns")
        return None

    ok  = df[df.correct == 1]["response_len"]
    err = df[df.correct == 0]["response_len"]

    r_len, p_len   = scipy_stats.pearsonr(df["response_len"], df["correct"])
    u_stat, p_mw   = scipy_stats.mannwhitneyu(ok, err, alternative="two-sided")
    d              = cohens_d(ok, err)
    r2             = r_len ** 2

    # Quartile breakdown
    df["len_q"] = pd.qcut(df["response_len"], 4, labels=["Q1", "Q2", "Q3", "Q4"])
    quartiles = []
    for q in ["Q1", "Q2", "Q3", "Q4"]:
        sub = df[df.len_q == q]
        quartiles.append({
            "quartile": q,
            "n":        len(sub),
            "mean_len": sub["response_len"].mean(),
            "accuracy": sub["correct"].mean(),
        })

    # GT class breakdown (confound check)
    gt_rows = []
    for gt in [-1, 0, 1]:
        sub = df[df.ground_truth == gt]
        if len(sub) == 0:
            continue
        gt_rows.append({
            "gt":       gt,
            "n":        len(sub),
            "mean_len": sub["response_len"].mean(),
            "accuracy": sub["correct"].mean(),
        })

    return {
        "name":      name,
        "n":         len(df),
        "n_ok":      len(ok),
        "n_err":     len(err),
        "mean_ok":   ok.mean(),
        "median_ok": ok.median(),
        "std_ok":    ok.std(),
        "mean_err":  err.mean(),
        "median_err":err.median(),
        "std_err":   err.std(),
        "diff":      ok.mean() - err.mean(),
        "r":         r_len,
        "p_pearson": p_len,
        "r2":        r2,
        "u_stat":    u_stat,
        "p_mw":      p_mw,
        "cohens_d":  d,
        "quartiles": quartiles,
        "gt_rows":   gt_rows,
        "df":        df,
    }

# ── figures ───────────────────────────────────────────────────────────────────

def fig_length_distribution(results: list[dict], output_dir: Path):
    """Box plots of response length for correct vs incorrect, per model."""
    n = len(results)
    fig, axes = plt.subplots(1, n, figsize=(3 * n, 5), sharey=False)
    if n == 1:
        axes = [axes]

    for ax, r in zip(axes, results):
        df = r["df"]
        ok_lens  = df[df.correct == 1]["response_len"].values
        err_lens = df[df.correct == 0]["response_len"].values
        bp = ax.boxplot(
            [ok_lens, err_lens],
            tick_labels=["Correct", "Incorrect"],
            patch_artist=True,
            medianprops=dict(color="white", linewidth=2),
            whiskerprops=dict(color="#6c7086"),
            capprops=dict(color="#6c7086"),
            flierprops=dict(marker=".", markersize=2, alpha=0.3, color="#6c7086"),
        )
        bp["boxes"][0].set_facecolor("#a6e3a1")
        bp["boxes"][1].set_facecolor("#f38ba8")
        ax.set_title(r["name"], fontsize=10, fontweight="bold")
        ax.set_ylabel("Response length (chars)" if ax == axes[0] else "")
        ax.tick_params(labelsize=8)
        ax.grid(axis="y", alpha=0.3)
        # Annotate mean diff
        ax.annotate(
            f"Δ={r['diff']:+.0f}",
            xy=(0.5, 0.97), xycoords="axes fraction",
            ha="center", va="top", fontsize=8, color="#cba6f7",
        )

    fig.suptitle("Response Length: Correct vs Incorrect", fontsize=12, fontweight="bold")
    fig.tight_layout()
    path = output_dir / "len_fig1_boxplot.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  len_fig1_boxplot.png")


def fig_quartile_accuracy(results: list[dict], output_dir: Path):
    """Accuracy by length quartile — one line per model."""
    fig, ax = plt.subplots(figsize=(7, 4))
    colors = plt.cm.tab10.colors

    for i, r in enumerate(results):
        qs = r["quartiles"]
        xs = [q["quartile"] for q in qs]
        ys = [q["accuracy"] * 100 for q in qs]
        ax.plot(xs, ys, marker="o", label=r["name"], color=colors[i % 10], linewidth=2)

    ax.set_xlabel("Response Length Quartile (Q1=shortest, Q4=longest)")
    ax.set_ylabel("Accuracy (%)")
    ax.set_title("Accuracy Drops as Response Gets Longer")
    ax.legend(fontsize=8, ncol=2)
    ax.grid(alpha=0.3)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f"{v:.0f}%"))
    fig.tight_layout()
    path = output_dir / "len_fig2_quartile_accuracy.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  len_fig2_quartile_accuracy.png")


def fig_cross_model_summary(results: list[dict], output_dir: Path):
    """Bar chart of mean length correct vs incorrect per model, with r annotated."""
    names     = [r["name"] for r in results]
    mean_ok   = [r["mean_ok"]  for r in results]
    mean_err  = [r["mean_err"] for r in results]
    rs        = [r["r"]        for r in results]

    x   = np.arange(len(names))
    w   = 0.35
    fig, ax = plt.subplots(figsize=(max(7, len(names) * 1.3), 5))
    b1 = ax.bar(x - w/2, mean_ok,  w, label="Correct",   color="#a6e3a1", edgecolor="none")
    b2 = ax.bar(x + w/2, mean_err, w, label="Incorrect", color="#f38ba8", edgecolor="none")

    # Annotate r above each pair
    for i, (r_val, xpos) in enumerate(zip(rs, x)):
        ax.text(xpos, max(mean_ok[i], mean_err[i]) + 20,
                f"r={r_val:.3f}", ha="center", fontsize=8, color="#cba6f7")

    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=20, ha="right", fontsize=9)
    ax.set_ylabel("Mean response length (chars)")
    ax.set_title("Mean Response Length by Outcome (all models)")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    path = output_dir / "len_fig3_cross_model.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  len_fig3_cross_model.png")


def fig_gt_class_length(results: list[dict], output_dir: Path):
    """Mean response length by ground-truth class — shows the confound."""
    n = len(results)
    fig, axes = plt.subplots(1, n, figsize=(3 * n, 4), sharey=False)
    if n == 1:
        axes = [axes]

    gt_colors = {-1: "#f38ba8", 0: "#89dceb", 1: "#a6e3a1"}
    gt_labels = {-1: "Anti-syn (-1)", 0: "Neutral (0)", 1: "Synergy (+1)"}

    for ax, r in zip(axes, results):
        gts   = [row["gt"]       for row in r["gt_rows"]]
        means = [row["mean_len"] for row in r["gt_rows"]]
        accs  = [row["accuracy"] for row in r["gt_rows"]]
        bars  = ax.bar(
            [gt_labels[g] for g in gts],
            means,
            color=[gt_colors[g] for g in gts],
        )
        # Annotate accuracy on bars
        for bar, acc in zip(bars, accs):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 10,
                f"{acc*100:.0f}%",
                ha="center", va="bottom", fontsize=8, color="white",
            )
        ax.set_title(r["name"], fontsize=10, fontweight="bold")
        ax.set_ylabel("Mean response length" if ax == axes[0] else "")
        ax.tick_params(axis="x", labelsize=7, rotation=15)
        ax.grid(axis="y", alpha=0.3)

    fig.suptitle("Mean Length by GT Class (% = accuracy for that class)", fontsize=11)
    fig.tight_layout()
    path = output_dir / "len_fig4_gt_class.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  len_fig4_gt_class.png")


# ── report ────────────────────────────────────────────────────────────────────

def write_report(results: list[dict], output_dir: Path):
    report_path = output_dir / "report.md"

    # Read existing report (from syntax_adherence.py) and strip any previous
    # length section so we can replace it cleanly
    existing = ""
    if report_path.exists():
        raw = report_path.read_text(encoding="utf-8")
        marker = "\n---\n\n## Response Length Analysis"
        existing = raw.split(marker)[0]
    else:
        existing = ""

    lines = []
    lines.append("\n---\n")
    lines.append("## Response Length Analysis\n")
    lines.append(
        "Across all models, incorrect predictions have significantly longer responses.\n"
        "This is a confound: models write more when pairs are harder (true synergies/anti-synergies),\n"
        "and harder pairs remain hard to classify regardless of response length.\n"
    )

    # Cross-model summary table
    lines.append("\n### Cross-Model Summary\n")
    lines.append("| Model | Acc | Mean (correct) | Mean (incorrect) | Diff | r | d | p (MWU) | sig |")
    lines.append("|-------|-----|----------------|-----------------|------|---|---|---------|-----|")
    for r in results:
        lines.append(
            f"| {r['name']} | {r['n_ok']/r['n']*100:.1f}% "
            f"| {r['mean_ok']:.0f} (σ={r['std_ok']:.0f}) "
            f"| {r['mean_err']:.0f} (σ={r['std_err']:.0f}) "
            f"| {r['diff']:+.0f} "
            f"| {r['r']:.4f} "
            f"| {r['cohens_d']:.3f} "
            f"| {r['p_mw']:.3g} "
            f"| {sig_label(r['p_mw'])} |"
        )

    # Per-model detail
    for r in results:
        lines.append(f"\n### {r['name']} — detail\n")

        lines.append("**Length by outcome**\n")
        lines.append("| | Mean | Median | Std |")
        lines.append("|--|------|--------|-----|")
        lines.append(f"| Correct   | {r['mean_ok']:.0f} | {r['median_ok']:.0f} | {r['std_ok']:.0f} |")
        lines.append(f"| Incorrect | {r['mean_err']:.0f} | {r['median_err']:.0f} | {r['std_err']:.0f} |")
        lines.append(f"\n- r(length, correct) = **{r['r']:.4f}**, p={r['p_pearson']:.3g} {sig_label(r['p_pearson'])}")
        lines.append(f"- Cohen's d = **{r['cohens_d']:.3f}** (correct vs incorrect)")
        lines.append(f"- r² = {r['r2']:.4f} ({r['r2']*100:.2f}% variance explained)")

        lines.append("\n**Accuracy by length quartile** (Q1=shortest, Q4=longest)\n")
        lines.append("| Quartile | n | Mean length | Accuracy |")
        lines.append("|----------|---|-------------|---------|")
        for q in r["quartiles"]:
            lines.append(
                f"| {q['quartile']} | {q['n']} | {q['mean_len']:.0f} | {q['accuracy']*100:.1f}% |"
            )

        lines.append("\n**Confound check: mean length and accuracy by GT class**\n")
        lines.append("| GT class | n | Mean length | Accuracy |")
        lines.append("|----------|---|-------------|---------|")
        for row in r["gt_rows"]:
            label = {-1: "Anti-syn (-1)", 0: "Neutral (0)", 1: "Synergy (+1)"}[row["gt"]]
            lines.append(
                f"| {label} | {row['n']} | {row['mean_len']:.0f} | {row['accuracy']*100:.1f}% |"
            )

    lines.append("\n---\n")
    lines.append("*Length analysis generated by `length_analysis.py`*\n")

    report_path.write_text(existing + "\n".join(lines), encoding="utf-8")
    print(f"  Appended length section to report.md")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Response length vs correctness analysis")
    grp = parser.add_mutually_exclusive_group()
    grp.add_argument("--model", nargs="+", metavar="MODEL",
                     help="One or more model short-names (e.g. gpt4o gpt54)")
    grp.add_argument("--all", action="store_true", help="Run on all models in datasets.json")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), metavar="DIR",
                        help=f"Output directory (default: {DEFAULT_OUTPUT})")
    args = parser.parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    all_models = list(list_model_datasets().keys())
    if args.all or (not args.model):
        model_names = all_models
    else:
        model_names = [m for m in args.model if m in all_models]
        unknown = [m for m in args.model if m not in all_models]
        if unknown:
            print(f"Warning: unknown models ignored: {unknown}")

    print("=" * 60)
    print("  Response Length Analysis")
    print(f"  Models : {', '.join(model_names)}")
    print(f"  Output : {output_dir}")
    print("=" * 60)

    results = []
    for name in model_names:
        print(f"\n[{name}]")
        r = analyze_model(name, output_dir)
        if r:
            results.append(r)
            print(f"  n={r['n']}  mean_ok={r['mean_ok']:.0f}  mean_err={r['mean_err']:.0f}"
                  f"  diff={r['diff']:+.0f}  r={r['r']:.4f}  d={r['cohens_d']:.3f}"
                  f"  p_mw={r['p_mw']:.3g} {sig_label(r['p_mw'])}")

    if not results:
        print("\nNo results — run syntax_adherence.py first to generate adherence CSVs.")
        sys.exit(1)

    print("\nSaving figures...")
    fig_length_distribution(results, output_dir)
    fig_quartile_accuracy(results, output_dir)
    fig_cross_model_summary(results, output_dir)
    fig_gt_class_length(results, output_dir)

    print("\nUpdating report...")
    write_report(results, output_dir)

    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  {'Model':<16} {'Corr(ok)':>9} {'Corr(err)':>10} {'Diff':>7} {'r':>7} {'d':>7} {'sig':>4}")
    print("  " + "-" * 58)
    for r in results:
        print(f"  {r['name']:<16} {r['mean_ok']:>9.0f} {r['mean_err']:>10.0f}"
              f" {r['diff']:>+7.0f} {r['r']:>7.4f} {r['cohens_d']:>7.3f}"
              f" {sig_label(r['p_mw']):>4}")
    print("=" * 60)
    print(f"\nAll output in: {output_dir}")


if __name__ == "__main__":
    main()
