services:
  - type: web
    name: sts-synergy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
